version: '2'
services:
  jenkins-docker-test:
    image: localhost:5000/jenkins-docker-test
    container_name: jenkins-docker-test
    ports:
      - "9000:9000"
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    expose:
      - "5432"
    environment:
      POSTGRES_DB: jenkinstest
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test